### ISSUE TITLE
GridFSInput/OutputStream

### ISSUE THREAD

**Issue by diabolicallabs** [st-h/vertx-mongo-streams#2]
Steve, would you be willing to donate your GridFSInputStream and GridFSOutputStream classes to the official vertx3 mongo project? I've added gridfs support to the official project using your classes. If you are willing, I'll add attribution to you and this project in the official code. If you don't want to donate, I'll reimplement in a different way or think of an alternative. No pressure, just a request. Thanks for your consideration.

David Bush dbush@redhat.com

**Comment by st-h** [comment]
Hi David.
Sorry about the late reply. Is this about vertx-mongo-client? Please feel free to reuse the code. Attributions are appreciated. However, just a thought: Would it be a viable solution to include this project via maven/gradle, so you will be able to take advantage of future improvements?

**Comment by diabolicallabs** [comment]
Yes it is the vertx-mongo-client. I can't include your project via maven. I tried that with one of my own projects and the maintainers said no. I'll surely watch what your doing and notice any comments you make in the Google group.

Would you mind including a license similar to the link below in this project just to make it clear we can use your code?

https://github.com/vert-x3/vertx-mongo-client/blob/master/LICENSE.txt

**Comment by st-h** [comment]
Just out of curiosity: Did they provide any reason for doing so? I don't really plan to use the google group for updates, so probably it's best if you watch the repository here.

Regarding the licence: I didn't want to impose any unnecessary limitations nor having to deal with licensing details, so this is put out under [WTFPL](http://www.wtfpl.net) as referenced in the `pom.xml`. As mentioned, attributions are appreciated, but there is nothing that actually forces you to do so.

**Comment by diabolicallabs** [comment]
They mentioned that they only wanted to use well recognized repositories and libraries like Apache, etc. My github repository didn't qualify I guess. 

Never mind the license. I didn't see that in the pom.

I'll should have the PR done today for them.
