### ISSUE TITLE
GridFSOutputStreamImpl can copy bytes beyond file boundary

### ISSUE THREAD

**Issue by antofar** [st-h/vertx-mongo-streams#3]
When a file is larger than the default mongo buffer size (4194304 bytes), the buffer size is limited to the default.
Unless the file size is aligned to that value, the last segment will be less than the byte[] wrapped by the buffer. The current implementation will copy the whole array, that contains illegal bytes after the file boundary.
[Reproducer](https://gist.github.com/antofar/c41eba1fecc45794775b8467ce6fcb30)

**Comment by st-h** [comment]
@antofar I am having troubles with the changes made here. The files streamed from mongo are corrupt if they exceed a certain size. I am not yet sure why this happening, but I wrote an integration test which shows this. I still need to tweak some things so it runs everywhere but I should be able to add that shortly. The test passes with the changes reverted.

**Comment by st-h** [comment]
I added the integration test I mentioned to the master branch, which displays the issue ( [test results here](https://travis-ci.org/st-h/vertx-mongo-streams) ). When run locally it expects a running mongo instance at default port. However, I haven't yet figured out what the actual cause might be.

**Comment by st-h** [comment]
I think the issue here being that we do handle the wrapped ByteBuffer which is instantiated by the mongo driver back to vertx. I don't think there is any guarantee when the content of the buffer actually is written to the http response, so any further modifications to the buffer by the mongo driver could be reflected in previous http packets, which haven't been written yet, leading to corrupt data. I would replace the wrappedBuffer with a copiedBuffer buffer, which fixes the failing integration test. 

@antofar What do you think?

**Comment by st-h** [comment]
Sorry for closing prematurely. Meant to add the fix to a branch first.

**Comment by antofar** [comment]
Hi @st-h your explanation is correct, I have just checked the mongo driver and it does indeed clear the buffer. The real issue is that the write stream does not return any future/promise on when the async operation is completed (internally the HttpResponse has a promise from the channel but that's not exposed) so we can't asynchronously callback mongo. This is really a pity because with large files that's a lot of copying but I don't see any other solution than the one you found.

PS. it would be good for the integration test to spin an embedded mongo (flapdoodle)

**Comment by st-h** [comment]
Thanks for the comment. I didn't hear about flapdoodle yet. Will look into it.
I just released version 1.2.1 which contains the fix. Couldn't find a way either to share the memory.
