### ISSUE TITLE
Visibility issue for internal queue

### ISSUE THREAD

**Issue by antofar** [st-h/vertx-mongo-streams#5]
The mongo thread could see an inconsistent state of the internal queue while the writer thread is filling the queue.

@st-h 
Hello, I have a PR ready for this. The refactoring is fairly intense as I fixed the concurrency issue as well as the boxing/unboxing garbage generation for the queue. 
When working with large files that's a lot of objects created.
Do you want to have a look?

**Comment by st-h** [comment]
@antofar yes, please let's have a look. Sounds like something that should be fixed. Do you have a test which shows the issue?

**Comment by antofar** [comment]
Harnessing a concurrent test would be a PITA. By and large if you reason about it, it should be clear.

**Comment by st-h** [comment]
@antofar Thank you for raising this issue and submitting the pull request. To my understanding the library currently lacks the necessary synchronisation in a multi threaded context. I just wrote a small test to illustrate that and took the seemingly least complicated approach by making use of synchronized blocks. I haven't yet had the time to fully look at your implementation, however I think the interesting point here is getting good performance with a preferably simple implementation. I'll try to set up a branch to compare different implementations and at least get an idea of what is happening performance wise.

**Comment by antofar** [comment]
Thank you for creating the library in the first place.
As I mentioned earlier, the reason why I replaced the Deque is the Boxing problem. GridFS was mainly created for files larger than 16Mb (otherwise a single mongo document would do), you see, the amount of objects created for a single stream is quite relevant, opening a 100Mb file would mean 100 millions objects created for sure, that would put a lot of pressure on the GC. 
In case you want to stick with the current solution, at least implement the write bypass, the current code always writes to the internal buffer before flushing out, if you see my PR I first check whether we have an output buffer ready. This case is relevant in particular for scenarios where mongo is running locally on an SSD disk and the input comes from a file upload for instance.

**Comment by st-h** [comment]
@antofar I will be happy to merge your PR. Thank you for contributing this. I really like what you did there. I misread your first comment, as there is an issue with the current PR and lots of objects, but it came apparent what you meant when I read your code.
