### ISSUE TITLE
Callback is nullified incorrectly on recursive callback in GridFSInputStream

### ISSUE THREAD

**Issue by antofar** [st-h/vertx-mongo-streams#9]
Stored call back could be nullified when recursive stack unrolls.
i.e. in a sequence of reads resulting in a call stack like:

  storeCallback
 doCallback
doCallback

When the recursion ends the bottom of the stack will nullify the callback stored by the top of the stack.

@st-h 
Sorry about this, I had an integration test with mongo running in my codebase but probably I didn't run maven install on the final revision before the PR.

A fix is on the way.

**Comment by st-h** [comment]
Thanks. No worries. I myself forgot to add my test which I used to verify the concurrency issue. Unfortunately the current implementation seems to write incorrect data. Would you mind to have a look at #11 ?
